browser:
  firefox: Firefox
  safari: 'Safari'
  opera: 'Opera'
  flock: 'Flock'
  internet_explorer: 'Internet Explorer'
  Seamonkey: 'Seamonkey'
  tor_browser: 'Tor Browser'
  gnu_icecat: 'GNU IceCat'
  crios: 'CriOS'
  tenfourfox: 'TenFourFox'
  seamonkey: 'SeaMonkey'
  blitzbot: 'B-l-i-t-z-B-O-T'
  kKonqueror: 'Konqueror'
  mobile: 'Mobile'
  netscape: 'Netscape'
  chrome: 'Chrome'
  dragon: 'Dragon'
  maxthon: 'Maxthon'
  i_browse: 'IBrowse'
  k_meleon: 'K-Meleon'
  google_bot: 'GoogleBot'
  minimo: 'Minimo'
  weltweitimnetz_browser: 'WeltweitimnetzBrowser'
  super_bot: 'SuperBot'
  terrawiz_bot: 'TerrawizBot'
  yodao_bot: 'YodaoBot'
  wyzo: 'Wyzo'
  grail: 'Grail'
  pycurl: 'PycURL'
  galaxy: 'Galaxy'
  enigma_fox: 'EnigmaFox'
  008: '008'
  abacho_bot: 'ABACHOBot'
  bimbot: 'Bimbot'
  covario_ids: 'Covario IDS'
  i_cab: 'iCab'
  k_kman: 'KKman'
  oregano: 'Oregano'
  world_wide_web: 'WorldWideWeb'
  vimprobable: 'Vimprobable'
  uzbl: 'uzbl'
  slim_browser: 'Slim Browser'
  omni_web: 'OmniWeb'
  rockmelt: 'Rockmelt'
  shiira: 'Shiira'
  swift: 'Swift'
  pale_moon: 'Pale Moon'
  camino: 'Camino'
  galeon: 'Galeon'
  sylera: 'Sylera'
os:
  Windows31: 'Windows 3.1'
  Windows95: 'Windows 95'
  Windows98: 'Windows 98'
  Windows2000: 'Windows 2000'
  WindowsNT: 'Windows NT'
  Linux242210mdk: 'Linux 2.4.22-10mdk'
  FreeBSD: 'FreeBSD'
  WindowsXP: 'Windows XP'
  WindowsVista: 'Windows Vista'
  RedhatLinux: 'Redhat Linux'
  Ubuntu: 'Ubuntu'
  Fedora: 'Fedora'
  AmigaOS: 'AmigaOS'
  BackTrackLinux: 'BackTrack Linux'
  iPad: 'iPad'
  BlackBerry: 'BlackBerry'
  Unix: 'Unix'
  CentOSLinux: 'CentOS Linux'
  DebianLinux: 'Debian Linux'
  Macintosh: 'Macintosh'
  Android: 'Android'
  iPhone: 'iPhone'
  WindowsNT 6.1: 'Windows NT 6.1'
  eOS: 'BeOS'
  OS105: 'OS 10.5'
  Nokia: 'Nokia'
  ArchLinux: 'Arch Linux'
  ArkLinux: 'Ark Linux'
  BitLinux: 'BitLinux'
  ConectivaMandriva: 'Conectiva (Mandriva)'
  CRUXLinux: 'CRUX Linux'
  DamnSmallLinux: 'Damn Small Linux'
  DeLiLinux: 'DeLi Linux'
  Ubuntu: 'Ubuntu'
  BigLinux: 'BigLinux'
  Edubuntu: 'Edubuntu'
  Fluxbuntu: 'Fluxbuntu'
  Freespire: 'Freespire'
  GNewSense: 'GNewSense'
  Gobuntu: 'Gobuntu'
  gOS: 'gOS'
  MintLinux: 'Mint Linux'
  Kubuntu: 'Kubuntu'
  Xubuntu: 'Xubuntu'
  ZeVenOS: 'ZeVenOS'
  Zebuntu: 'Zebuntu'
  DemoLinux: 'DemoLinux'
  Dreamlinux: 'Dreamlinux'
  DualOS: 'DualOS'
  eLearnix: 'eLearnix'
  FeatherLinux: 'Feather Linux'
  Famelix: 'Famelix'
  FeniX: 'FeniX'
  Gentoo: 'Gentoo'
  GoboLinux: 'GoboLinux'
  GNUstep: 'GNUstep'
  InsigneLinux: 'Insigne Linux'
  Kalango: 'Kalango'
  KateOS: 'KateOS'
  Knoppix: 'Knoppix'
  Kurumin: 'Kurumin'
  Dizinha: 'Dizinha'
  TupiServer: 'TupiServer'
  Linspire: 'Linspire'
  Litrix: 'Litrix'
  Mandrake: 'Mandrake'
  Mandriva: 'Mandriva'
  MEPIS: 'MEPIS'
  MusixGNULinux: 'Musix GNU Linux'
  MusixBR: 'Musix-BR'
  OneBaseGo: 'OneBase Go'
  openSuSE: 'openSuSE'
  pQuiLinux: 'pQui Linux'
  PCLinuxOS: 'PCLinuxOS'
  Plaszma OS: 'Plaszma OS'
  PuppyLinux: 'Puppy Linux'
  QiLinux: 'QiLinux'
  RedHatLinux: 'Red Hat Linux'
  RedHatEnterpriseLinux: 'Red Hat Enterprise Linux'
  CentOS: 'CentOS'
  Fedora: 'Fedora'
  Resulinux: 'Resulinux'
  Rxart: 'Rxart'
  SabayonLinux: 'Sabayon Linux'
  SAMDesktop: 'SAM Desktop'
  Satux: 'Satux'
  Slackware: 'Slackware'
  GoblinX: 'GoblinX'
  Slax: 'Slax'
  Zenwalk: 'Zenwalk'
  SuSE: 'SuSE'
  CaixaMágica: 'Caixa Mágica'
  HPUX: 'HP-UX'
  IRIX: 'IRIX'
  OSF1: 'OSF/1'
  OS9: 'OS-9'
  POSYS: 'POSYS'
  QNX: 'QNX'
  Solaris: 'Solaris'
  OpenSolaris: 'OpenSolaris'
  SunOS: 'SunOS'
  SCOUNIX: 'SCO UNIX'
  Tropix: 'Tropix'
  EROS: 'EROS'
  Tru64: 'Tru64'
  DigitalUNIX: 'Digital UNIX'
  Ultrix: 'Ultrix'
  UniCOS: 'UniCOS'
  UNIflex: 'UNIflex'
  MicrosoftXenix: 'Microsoft Xenix'
  zOS: 'z/OS'
  Xinu: 'Xinu'
  ResearchUnix: 'Research Unix'
  InfernoOS: 'InfernoOS'
locale:
  cs-CZ: 'cs-CZ'
  en-US: 'en-US'
  sk-SK: 'sk-SK'
  pt-BR: 'pt-BR'
  sq_AL: 'sq_AL'
  sq: 'sq'
  ar_DZ: 'ar_DZ'
  ar_BH: 'ar_BH'
  ar_EG: 'ar_EG'
  ar_IQ: 'ar_IQ'
  ar_JO: 'ar_JO'
  ar_KW: 'ar_KW'
  ar_LB: 'ar_LB'
  ar_LY: 'ar_LY'
  ar_MA: 'ar_MA'
  ar_OM: 'ar_OM'
  ar_QA: 'ar_QA'
  ar_SA: 'ar_SA'
  ar_SD: 'ar_SD'
  ar_SY: 'ar_SY'
  ar_TN: 'ar_TN'
  ar_AE: 'ar_AE'
  ar_YE: 'ar_YE'
  ar: 'ar'
  be_BY: 'be_BY'
  be: 'be'
  bg_BG: 'bg_BG'
  bg: 'bg'
  ca_ES: 'ca_ES'
  ca: 'ca'
  zh_CN: 'zh_CN'
  zh_HK: 'zh_HK'
  zh_SG: 'zh_SG'
  zh_TW: 'zh_TW'
  zh: 'zh'
  hr_HR: 'hr_HR'
  hr: 'hr'
  cs_CZ: 'cs_CZ'
  cs: 'cs'
  da_DK: 'da_DK'
  da: 'da'
  nl_BE: 'nl_BE'
  nl_NL: 'nl_NL'
  nl: 'nl'
  en_AU: 'en_AU'
  en_CA: 'en_CA'
  en_IN: 'en_IN'
  en_IE: 'en_IE'
  en_MT: 'en_MT'
  en_NZ: 'en_NZ'
  en_PH: 'en_PH'
  en_SG: 'en_SG'
  en_ZA: 'en_ZA'
  en_GB: 'en_GB'
  en_US: 'en_US'
  en: 'en'
  et_EE: 'et_EE'
  et: 'et'
  fi_FI: 'fi_FI'
  fi: 'fi'
  fr_BE: 'fr_BE'
  fr_CA: 'fr_CA'
  fr_FR: 'fr_FR'
  fr_LU: 'fr_LU'
  fr_CH: 'fr_CH'
  fr: 'fr'
  de_AT: 'de_AT'
  de_DE: 'de_DE'
  de_LU: 'de_LU'
  de_CH: 'de_CH'
  de: 'de'
  el_CY: 'el_CY'
  el_GR: 'el_GR'
  el: 'el'
  iw_IL: 'iw_IL'
  iw: 'iw'
  hi_IN: 'hi_IN'
  hu_HU: 'hu_HU'
  hu: 'hu'
  is_IS: 'is_IS'
  is: 'is'
  in_ID: 'in_ID'
  in: 'in'
  ga_IE: 'ga_IE'
  ga: 'ga'
  it_IT: 'it_IT'
  it_CH: 'it_CH'
  it: 'it'
  ja_JP: 'ja_JP'
  ja_JP_JP: 'ja_JP_JP'
  ja: 'ja'
  ko_KR: 'ko_KR'
  ko: 'ko'
  lv_LV: 'lv_LV'
  lv: 'lv'
  lt_LT: 'lt_LT'
  lt: 'lt'
  mk_MK: 'mk_MK'
  mk: 'mk'
  ms_MY: 'ms_MY'
  ms: 'ms'
  mt_MT: 'mt_MT'
  mt: 'mt'
  no_NO: 'no_NO'
  no_NO_NY: 'no_NO_NY'
  no: 'no'
  pl_PL: 'pl_PL'
  pl: 'pl'
  pt_PT: 'pt_PT'
  pt: 'pt'
  ro_RO: 'ro_RO'
  ro: 'ro'
  ru_RU: 'ru_RU'
  ru: 'ru'
  sr_BA: 'sr_BA'
  sr_ME: 'sr_ME'
  sr_CS: 'sr_CS'
  sr_RS: 'sr_RS'
  sr: 'sr'
  sk_SK: 'sk_SK'
  sk: 'sk'
  sl_SI: 'sl_SI'
  sl: 'sl'
  es_AR: 'es_AR'
  es_BO: 'es_BO'
  es_CL: 'es_CL'
  es_CO: 'es_CO'
  es_CR: 'es_CR'
  es_DO: 'es_DO'
  es_EC: 'es_EC'
  es_SV: 'es_SV'
  es_GT: 'es_GT'
  es_HN: 'es_HN'
  es_MX: 'es_MX'
  es_NI: 'es_NI'
  es_PA: 'es_PA'
  es_PY: 'es_PY'
  es_PE: 'es_PE'
  es_PR: 'es_PR'
  es_ES: 'es_ES'
  es_US: 'es_US'
  es_UY: 'es_UY'
  es_VE: 'es_VE'
  es: 'es'
  sv_SE: 'sv_SE'
  sv: 'sv'
  th_TH: 'th_TH'
  th_TH_TH: 'th_TH_TH'
  th: 'th'
  tr_TR: 'tr_TR'
  tr: 'tr'
  uk_UA: 'uk_UA'
  uk: 'uk'
  vi_VN: 'vi_VN'
  vi: 'vi'
