domain:
  com: 'www.google.com'
  ac: 'www.google.ac'
  om: 'www.google.com.om'
  ad: 'www.google.ad'
  ae: 'www.google.ae'
  af: 'www.google.com.af'
  ag: 'www.google.com.ag'
  ai: 'www.google.com.ai'
  am: 'www.google.am'
  it_ao: 'www.google.it.ao'
  ar: 'www.google.com.ar'
  cat: 'www.google.cat'
  as: 'www.google.as'
  at: 'www.google.at'
  au: 'www.google.com.au'
  az: 'www.google.az'
  ba: 'www.google.ba'
  bd: 'www.google.com.bd'
  be: 'www.google.be'
  bf: 'www.google.bf'
  bg: 'www.google.bg'
  bh: 'www.google.com.bh'
  bi: 'www.google.bi'
  bj: 'www.google.bj'
  bn: 'www.google.com.bn'
  bo: 'www.google.com.bo'
  br: 'www.google.com.br'
  bs: 'www.google.bs'
  co_bw: 'www.google.co.bw'
  by: 'www.google.com.by'
  bz: 'www.google.com.bz'
  ca: 'www.google.ca'
  kh: 'www.google.com.kh'
  cc: 'www.google.cc'
  cd: 'www.google.cd'
  cf: 'www.google.cf'
  cn: 'www.google.cn'
  co: 'www.google.com.co'
  co_nz: 'www.google.co.nz'
  cg: 'www.google.cg'
  ch: 'www.google.ch'
  ci: 'www.google.ci'
  co_ck: 'www.google.co.ck'
  cl: 'www.google.cl'
  cm: 'www.google.cm'
  co_cr: 'www.google.co.cr'
  cu: 'www.google.com.cu'
  cv: 'www.google.cv'
  cz: 'www.google.cz'
  de: 'www.google.de'
  nu: 'www.google.nu'
  dj: 'www.google.dj'
  dk: 'www.google.dk'
  dm: 'www.google.dm'
  do: 'www.google.com.do'
  dz: 'www.google.dz'
  no: 'www.google.no'
  ec: 'www.google.com.ec'
  ee: 'www.google.ee'
  eg: 'www.google.com.eg'
  es: 'www.google.es'
  et: 'www.google.com.et'
  np: 'www.google.com.np'
  fi: 'www.google.fi'
  fj: 'www.google.com.fj'
  fm: 'www.google.fm'
  fr: 'www.google.fr'
  ga: 'www.google.ga'
  nl: 'www.google.nl'
  ge: 'www.google.ge'
  gf: 'www.google.gf'
  gg: 'www.google.gg'
  gh: 'www.google.com.gh'
  gi: 'www.google.com.gi'
  nr: 'www.google.nr'
  gl: 'www.google.gl'
  gm: 'www.google.gm'
  gp: 'www.google.gp'
  gr: 'www.google.gr'
  gt: 'www.google.com.gt'
  ni: 'www.google.com.ni'
  gy: 'www.google.gy'
  hk: 'www.google.com.hk'
  hn: 'www.google.hn'
  hr: 'www.google.hr'
  ht: 'www.google.ht'
  ng: 'www.google.com.ng'
  hu: 'www.google.hu'
  co_id: 'www.google.co.id'
  iq: 'www.google.iq'
  ie: 'www.google.ie'
  co_il: 'www.google.co.il'
  nf: 'www.google.com.nf'
  im: 'www.google.im'
  co_in: 'www.google.co.in'
  io: 'www.google.io'
  is: 'www.google.is'
  it: 'www.google.it'
  ne: 'www.google.ne'
  je: 'www.google.je'
  jm: 'www.google.com.jm'
  jo: 'www.google.jo'
  co_jp: 'www.google.co.jp'
  co_ke: 'www.google.co.ke'
  na: 'www.google.com.na'
  ki: 'www.google.ki'
  kg: 'www.google.kg'
  co_kr: 'www.google.co.kr'
  kw: 'www.google.com.kw'
  kz: 'www.google.kz'
  co_mz: 'www.google.co.mz'
  la: 'www.google.la'
  lb: 'www.google.com.lb'
  lc: 'www.google.com.lc'
  li: 'www.google.li'
  lk: 'www.google.lk'
  my: 'www.google.com.my'
  co_ls: 'www.google.co.ls'
  lt: 'www.google.lt'
  lu: 'www.google.lu'
  lv: 'www.google.lv'
  ly: 'www.google.com.ly'
  mx: 'www.google.com.mx'
  co_ma: 'www.google.co.ma'
  md: 'www.google.md'
  me: 'www.google.me'
  mg: 'www.google.mg'
  mk: 'www.google.mk'
  mw: 'www.google.mw'
  ml: 'www.google.ml'
  mn: 'www.google.mn'
  ms: 'www.google.ms'
  mt: 'www.google.com.mt'
  mu: 'www.google.mu'
  mv: 'www.google.mv'
  pa: 'www.google.com.pa'
  pe: 'www.google.com.pe'
  ph: 'www.google.com.ph'
  pk: 'www.google.com.pk'
  pn: 'www.google.pn'
  pr: 'www.google.com.pr'
  ps: 'www.google.ps'
  pt: 'www.google.pt'
  py: 'www.google.com.py'
  qa: 'www.google.com.qa'
  ro: 'www.google.ro'
  rs: 'www.google.rs'
  ru: 'www.google.ru'
  rw: 'www.google.rw'
  sa: 'www.google.com.sa'
  sb: 'www.google.com.sb'
  sc: 'www.google.sc'
  se: 'www.google.se'
  sg: 'www.google.com.sg'
  sh: 'www.google.sh'
  si: 'www.google.si'
  sk: 'www.google.sk'
  sl: 'www.google.com.sl'
  sn: 'www.google.sn'
  .sm: 'www.google.sm'
  so: 'www.google.so'
  st: 'www.google.st'
  sv: 'www.google.com.sv'
  td: 'www.google.td'
  tg: 'www.google.tg'
  th: 'www.google.co.th'
  tk: 'www.google.tk'
  tl: 'www.google.tl'
  tm: 'www.google.tm'
  to: 'www.google.to'
  tn: 'www.google.com.tn'
  tr: 'www.google.com.tr'
  tt: 'www.google.tt'
  tw: 'www.google.com.tw'
  tz: 'www.google.co.tz'
  ua: 'www.google.com.ua'
  ug: 'www.google.co.ug'
  uk: 'www.google.co.uk'
  us: 'www.google.us'
  uy: 'www.google.com.uy'
  uz: 'www.google.co.uz'
  vc: 'www.google.com.vc'
  ve: 'www.google.co.ve'
  vg: 'www.google.vg'
  vi: 'www.google.co.vi'
  vn: 'www.google.com.vn'
  vu: 'www.google.vu'
  ws: 'www.google.ws'
  za: 'www.google.co.za'
  zm: 'www.google.co.zm'
  zw: 'www.google.co.zw'
