domain:
  Adzuna: 'Adzuna'
  Bixee: 'Bixee'
  CareerBuilder: 'CareerBuilder'
  Craigslist: 'Craigslist'
  Dice: 'Dice'
  Eluta.ca: 'Eluta.ca'
  Hotjobs: 'Hotjobs'
  JobStreet: 'JobStreet'
  Incruit: 'Incruit'
  Indeed: 'Indeed'
  Glassdoor: 'Glassdoor'
  LinkUp: 'LinkUp'
  Monster: 'Monster'
  Naukri: 'Naukri'
  Yahoo: 'Yahoo'
  Legal: 'Legal'
  GoogleScholar: 'GoogleScholar'
  Lexis: 'Lexis'
  Manupatra: 'Manupatra'
  Quicklaw: 'Quicklaw'
  WestLaw: 'WestLaw'
  Medical: 'Medical'
  BingHealth: 'BingHealth'
  Bioinformatic: 'Bioinformatic'
  CiteAb: 'CiteAb'
  EB-eye: 'EB-eye'
  Entrez: 'Entrez'
  mtv: 'mtv'
  ubuntu: 'ubuntu'
  GenieKnows: 'GenieKnows'
  GoPubMed: 'GoPubMed'
  Healia: 'Healia'
  Healthline: 'Healthline'
  Nextbio: 'Nextbio'
  PubGene: 'PubGene'
  Quertle: 'Quertle'
  Searchmedica: 'Searchmedica'
  WebMD: 'WebMD'
  News: 'News'
  BingNews: 'BingNews'
  Daylife: 'Daylife'
  GoogleNews: 'GoogleNews'
  aol: 'aol'
  microsoft: 'microsoft'
  MagPortal: 'MagPortal'
  Newslookup: 'Newslookup'
  Nexis: 'Nexis'
  Topix: 'Topix'
  Trapit: 'Trapit'
  YahooNews: 'YahooNews'
  People: 'People'
  Comfibook: 'Comfibook'
  Ex.plode: 'Ex.plode'
  InfoSpace: 'InfoSpace'
  PeekYou: 'PeekYou'
  Spock: 'Spock'
  Spokeo: 'Spokeo'
  WorldwideHelpers: 'WorldwideHelpers'
  iPhone: 'iPhone'
  Zabasearch: 'Zabasearch'
  ZoomInfo: 'ZoomInfo'
  Fizber: 'Fizber'
  HotPads: 'HotPads'
  Realtor: 'Realtor'
  Redfin: 'Redfin'
  Rightmove: 'Rightmove'
  Trulia: 'Trulia'
  Zillow: 'Zillow'
  Zoopla: 'Zoopla'
tld:
  aero: 'aero'
  arpa: 'arpa'
  biz: 'biz'
  com: 'com'
  coop: 'coop'
  edu: 'edu'
  gov: 'gov'
  info: 'info'
  int: 'int'
  mil: 'mil'
  museum: 'museum'
  name: 'name'
  net: 'net'
  org: 'org'
  pro: 'pro'
  tel: 'tel'
file:
  admin: 'admin'
  index: 'index'
  wp-admin: 'wp-admin'
  info: 'info'
  shop: 'shop'
  file: 'file'
  out: 'out'
  open: 'open'
  news: 'news'
  add: 'add'
  profile: 'profile'
  search: 'search'
  open: 'open'
  photo: 'photo'
  insert: 'insert'
  view: 'view'
ext:
  exe: 'exe'
  php: 'php'
  asp: 'asp'
  aspx: 'aspx'
  jsf: 'jsf'
  html: 'html'
  htm: 'htm'
  lua: 'lua'
  log: 'log'
  cgi: 'cgi'
  sh: 'sh'
  css: 'css'
  py: 'py'
  sql: 'sql'
  xml: 'xml'
  rss: 'rss'
folder:
  App_Files: App_Files
  Assets: 'Assets'
  CFFileServlet: 'CFFileServlet'
  CFIDE: 'CFIDE'
  Communication: 'Communication'
  Computers: 'Computers'
  CoreAdminHome: 'CoreAdminHome'
  CoreHome: 'CoreHome'
  Crawler: 'Crawler'
  Creator: 'Creator'
  DECOM: 'DECOM'
  Dashboard: 'Dashboard'
  Drives: 'Drives'
  Dynamic: 'Dynamic'
  FCKeditor: 'FCKeditor'
  Feedback: 'Feedback'
  Files: 'Files'
  Flash: 'Flash'
  Forms: 'Forms'
  Help: 'Help'
  ICEcore: 'ICEcore'
  IO: 'IO'
  Image: 'Image'
  JPG: 'JPG'
  getold: 'getold'
  JSP: 'JSP'
  KFSI: 'KFSI'
  Laguna: 'Laguna'
  Login: 'Login'
  Motors: 'Motors'
  MultiSites: 'MultiSites'
  NR: 'NR'
  OCodger: 'OCodger'
  RSS: 'RSS'
  Safety: 'Safety'
  Smarty: 'Smarty'
  Software: 'Software'
  Static: 'Static'
  Stress: 'Stress'
  getfull: 'getfull'
  Sugarcrm: 'Sugarcrm'
  Travel: 'Travel'
  UPLOAD: 'UPLOAD'
  Urussanga: 'Urussanga'
  UserFiles: 'UserFiles'
  __tpl: '__tpl'
  _fckeditor: '_fckeditor'
  _info: '_info'
  _machine: '_machine'
  _plugins: '_plugins'
  _sample: '_sample'
  _samples: '_samples'
  postmost: 'postmost'
  _source: '_source'
  _testcases: '_testcases'
  aaa: 'aaa'
  abelardoluz: 'abelardoluz'
  aberlardoluz: 'aberlardoluz'
  aborto: 'aborto'
  about: 'about'
  aboutus: 'aboutus'
  abuse: 'abuse'
  abusers: 'abusers'
  ac_drives: 'ac_drives'
  acabamentos: 'acabamentos'
  mail: 'mail'
  academias: 'academias'
  acao: 'acao'
  acartpro: 'acartpro'
  acatalog: 'acatalog'
  acc: 'acc'
  acc_auto_del: 'acc_auto_del'
  acc_beep_ken: 'acc_beep_ken'
  acc_beep_time: 'acc_beep_time'
  acc_ch_mail: 'acc_ch_mail'
  acc_fc_prsc: 'acc_fc_prsc'
  accounts: 'accounts'
  validar: 'validar'
  acc_html_mark: 'acc_html_mark'
  acc_html_rand: 'acc_html_rand'
  acc_lan_page: 'acc_lan_page'
  acc_pic_html: 'acc_pic_html'
  acc_profol: 'acc_profol'
  acc_soft_link: 'acc_soft_link'
  acc_ssd_page: 'acc_ssd_page'
  acc_syun_ei: 'acc_syun_ei'
  german: 'german'
  intranet: 'intranet'
  old: 'old'
  acc_time_go: 'acc_time_go'
  acc_wbcreator: 'acc_wbcreator'
  accept: 'accept'
  accepted: 'accepted'
  acceso: 'acceso'
  access: 'access'
  accessibility: 'accessibility'
  accessories: 'accessories'
  acciones: 'acciones'
  acclg: 'acclg'
  account: 'account'
  paste: 'paste'
  paste22: 'paste22'
  acessorios: 'acessorios'
  acontece: 'acontece'
  acougueiro: 'acougueiro'
  acoustic: 'acoustic'
  act: 'act'
  action: 'action'
  activate: 'activate'
  active: 'active'
  activeden: 'activeden'
  activism: 'activism'
  actualit: 'actualit'
  actuators: 'actuators'
  ad: 'ad'
  informatica: 'informatica'
  ad_division: 'ad_division'
  ad_rate: 'ad_rate'
  adapter: 'adapter'
  adapters: 'adapters'
  adaptive: 'adaptive'
  adaptivei: 'adaptivei'
  adatmentes: 'adatmentes'
  adbanner: 'adbanner'
  adblock: 'adblock'
  adboard: 'adboard'
  adclick: 'adclick'
  add-ons: 'add-ons'
  add: 'add'
  delete: 'delete'
  added: 'added'
  addon: 'addon'
  address: 'address'
  adduser: 'adduser'
  adfree: 'adfree'
  adhoc: 'adhoc'
  adinfo: 'adinfo'
  adios_papa: 'adios_papa'
  adlink: 'adlink'
  adlinks: 'adlinks'
  acc_folder_vw: 'acc_folder_vw'
  acc_syun_su: 'acc_syun_su'
locale:
  ac: 'ac'
  ad: 'ad'
  ae: 'ae'
  af: 'af'
  ag: 'ag'
  al: 'al'
  am: 'am'
  an: 'an'
  ao: 'ao'
  aq: 'aq'
  ar: 'ar'
  as: 'as'
  at: 'at'
  au: 'au'
  aw: 'aw'
  az: 'az'
  ba: 'ba'
  bb: 'bb'
  bd: 'bd'
  be: 'be'
  bf: 'bf'
  bg: 'bg'
  bh: 'bh'
  bi: 'bi'
  bj: 'bj'
  bm: 'bm'
  bn: 'bn'
  bw: 'bw'
  by: 'by'
  bz: 'bz'
  ca: 'ca'
  cc: 'cc'
  cd: 'cd'
  cf: 'cf'
  cg: 'cg'
  ch: 'ch'
  ci: 'ci'
  ck: 'ck'
  cl: 'cl'
  cm: 'cm'
  cn: 'cn'
  co: 'co'
  cr: 'cr'
  cu: 'cu'
  cv: 'cv'
  cx: 'cx'
  cy: 'cy'
  cz: 'cz'
  de: 'de'
  dj: 'dj'
  dk: 'dk'
  dm: 'dm'
  do: 'do'
  dz: 'dz'
  bo: 'bo'
  br: 'br'
  ec: 'ec'
  ee: 'ee'
  eg: 'eg'
  er: 'er'
  es: 'es'
  et: 'et'
  eu: 'eu'
  fi: 'fi'
  fj: 'fj'
  fk: 'fk'
  fm: 'fm'
  fo: 'fo'
  fr: 'fr'
  ga: 'ga'
  gb: 'gb'
  gd: 'gd'
  ge: 'ge'
  gf: 'gf'
  gg: 'gg'
  gh: 'gh'
  gi: 'gi'
  gl: 'gl'
  gm: 'gm'
  gn: 'gn'
  gp: 'gp'
  gq: 'gq'
  gr: 'gr'
  bs: 'bs'
  bt: 'bt'
  gs: 'gs'
  gt: 'gt'
  gu: 'gu'
  gw: 'gw'
  gy: 'gy'
  hk: 'hk'
  hm: 'hm'
  hn: 'hn'
  hr: 'hr'
  ht: 'ht'
  hu: 'hu'
  id: 'id'
  ie: 'ie'
  il: 'il'
  im: 'im'
  in: 'in'
  io: 'io'
  iq: 'iq'
  ir: 'ir'
  is: 'is'
  it: 'it'
  je: 'je'
  jm: 'jm'
  jo: 'jo'
  jp: 'jp'
  ke: 'ke'
  kg: 'kg'
  bv: 'bv'
  kh: 'kh'
  ki: 'ki'
  km: 'km'
  kn: 'kn'
  kr: 'kr'
  kw: 'kw'
  ky: 'ky'
  kz: 'kz'
  la: 'la'
  lb: 'lb'
  lc: 'lc'
  li: 'li'
  lk: 'lk'
  lr: 'lr'
  ls: 'ls'
  lt: 'lt'
  lu: 'lu'
  lv: 'lv'
  ly: 'ly'
  ma: 'ma'
  mc: 'mc'
  md: 'md'
  me: 'me'
  mg: 'mg'
  mh: 'mh'
  mk: 'mk'
  ml: 'ml'
  mm: 'mm'
  mn: 'mn'
  mo: 'mo'
  mp: 'mp'
  mq: 'mq'
  mr: 'mr'
  ms: 'ms'
  mt: 'mt'
  mu: 'mu'
  mv: 'mv'
  mw: 'mw'
  mx: 'mx'
  my: 'my'
  mz: 'mz'
  nb: 'nb'
  nc: 'nc'
  ne: 'ne'
  nf: 'nf'
  ng: 'ng'
  ni: 'ni'
  nl: 'nl'
  no: 'no'
  np: 'np'
  nr: 'nr'
  nu: 'nu'
  nz: 'nz'
  om: 'om'
  pa: 'pa'
  pe: 'pe'
  pf: 'pf'
  pg: 'pg'
  ph: 'ph'
  pk: 'pk'
  pl: 'pl'
  pm: 'pm'
  pn: 'pn'
  pr: 'pr'
  ps: 'ps'
  pt: 'pt'
  pw: 'pw'
  py: 'py'
  qa: 'qa'
  re: 're'
  ro: 'ro'
  ru: 'ru'
  rw: 'rw'
  sa: 'sa'
  sb: 'sb'
  sc: 'sc'
  sd: 'sd'
  se: 'se'
  sg: 'sg'
  sh: 'sh'
  si: 'si'
  sj: 'sj'
  sk: 'sk'
  sl: 'sl'
  sm: 'sm'
  sn: 'sn'
  so: 'so'
  sr: 'sr'
  ss: 'ss'
  st: 'st'
  su: 'su'
  sv: 'sv'
  sy: 'sy'
  sz: 'sz'
  tc: 'tc'
  td: 'td'
  tf: 'tf'
  tg: 'tg'
  th: 'th'
  tj: 'tj'
  tk: 'tk'
  tl: 'tl'
  tm: 'tm'
  tn: 'tn'
  to: 'to'
  tr: 'tr'
  tt: 'tt'
  tv: 'tv'
  tw: 'tw'
  tz: 'tz'
  ua: 'ua'
  ug: 'ug'
  uk: 'uk'
  um: 'um'
  us: 'us'
  uy: 'uy'
  uz: 'uz'
  va: 'va'
  vc: 'vc'
  ve: 've'
  vg: 'vg'
  vi: 'vi'
  vn: 'vn'
  vu: 'vu'
  wf: 'wf'
  ws: 'ws'
  ye: 'ye'
  yt: 'yt'
  yu: 'yu'
  za: 'za'
  zm: 'zm'
  zw: 'zw'
  ai: 'ai'
