version: '3'
services:
  app:
    build: .
    command: /etc/init.d/tor start && /etc/init.d/privoxy start
    volumes:
      - .:/myapp
      - /myapp/tmp
      - ./docker/etc/privoxy/config:/etc/privoxy/config
    # ports:
    #   - "3000:3000"
    #   - "1080:1080"
    # depends_on:
    #   - db