target: http://testphp.vulnweb.com
verbose: false
debug: false
proxy:
  name: tor
  use: false
  hostname: http://localhost
  port: 9050
search:
  persist:
    number: 5
  result:
    per_page: 1500
query:
  delay: 1.5
  verbose: false
locale: pt-BR