target: http://testphp.vulnweb.com
verbose: false
debug: false
dork:
  directory: dorks
proxy:
  use: false
  hostname: http://localhost
  port: 9050
output:
  directory: output
search:
  persist:
    number: 5
  result:
    per_page: 1500
query:
  delay: 1.5
  verbose: false
locale: pt-BR