target: http://testphp.vulnweb.com
verbose: false
debug: false
dork:
  directory: dorks
  categories: Vulnerable Files, Vulnerable Servers, Error Messages, Network or vulnerability data, Various Online Devices, Files containing passwords, Sensitive Online Shopping Info, Files containing juicy info, Pages containing login portals, Advisories and Vulnerabilities, Files containing usernames, Footholds, sensitive Directories, Web Server Detection 
expr:
  operator:
    allinanchor:
      title: allinanchor
      summary: All query words must appear in anchor text of links to the page.
      exemple: allinanchor:useful parenting sites (Search for pages that are called useful parenting sites by others.)
    allintext:
      title: allintext
      summary: All query words must appear the in text of the page.
      exemple: allintext:ingredients cilantro chicken lime (Search for recipes with these three ingredients.)
    allintitle:
      title: allintitle
      summary: All query words must appear in the title of the page.
      exemple: 'allintitle: Google Advanced Operators (Search for pages with titles containing "Google," "Advanced,", and "Operators".)'
    allinurl:
      title: allinurl
      summary: All query words must appear in the URL.
      exemple: allinurl:pez faq (Search for pages containing the words pez & faq in the URL.)
    cache:
      title: cache
      summary: Display Google's cached version of a web page.
      exemple: cache:www.irs.gov (Show Google's cached version of the US Internal Revenue Service home page.)
    define:
      title: define
      summary:
      exemple:
    filetype:
      title: filetype
      summary:
      exemple:
    id:
      title: id
      summary: Find info about a page.
      exemple: info:www.theonion.com (Find information about The Onion website.)
    inanchor:
      title: inanchor
      summary: Terms must appear in anchor text of links to the page.
      exemple: restaurants Portland inanchor:kid-friendly (Search for pages on Portland restaurants for which links to the page say they are "kid friendly.")
    info:
      title: info
      summary: Find info about a page.
      exemple: info:www.theonion.com (Find information about The Onion website.)
    intext:
      title: intext
      summary: The terms must appear in the text of the page.
      exemple: Dan Shugar intext:Powerlight (Find pages mentioning Dan Shugar where his company, Powerlight, is included in the text of the page, i.e., less likely to be from the corporate website.)
    intitle:
      title: intitle
      summary: The terms must appear in the title of the page.
      exemple: movies comedy intitle:top ten (Search for pages with the words movie and comedy that include top ten in the title of the page.)
    inurl:
      title: inurl
      summary: The terms must appear in the URL of the page.
      exemple: pharmaceutical inurl:investor (Search for pages in which the URL contains the word investor.)
    phonebook:
      title: phonebook
      summary:
      exemple:
    related:
      title: related
      summary: List web pages that are similar or related to the URL.
      exemple: related:www.healthfinder.gov (Find websites related to the Healthfinder website.)
    ext:
      title: ext
      summary:
      exemple:
    location:
      title: location
      summary: Find News articles from sources located in the specified location. (Restrict Search to Google News)
      exemple: queen location:uk (Find British news articles on the Queen.)
    source:
      title: source
      summary: Find News articles from specified sources. (Restrict Search to Google News)
      exemple: peace source:ha_aretz (Show articles on peace from the Israeli newspaper Ha'aretz.)
    author:
      title: author
      summary: Find Groups messages from the specified author. (Restrict Search to Google Groups)
      exemple: flying author:Hamish author:Reid (Search for Hamish Reid's articles on flying.)
    group:
      title: group
      summary: Find Groups messages from the specified newsgroup. (Restrict Search to Google Groups)
      exemple: ivan doig group:rec.arts.books (Search for postings about Ivan Doig in the group rec.arts.books.)
    insubject:
      title: insubject
      summary: Find Groups messages containing crazy quilts in the subject. (Restrict Search to Google Groups)
      exemple: insubject:"crazy quilts" (Find articles containing crazy quilts in the subject line.)
proxy:
  use: false
  hostname: http://localhost
  port: 9050
output:
  directory: output
search:
  persist:
    number: 5
  result:
    per_page: 1500
query:
  delay: 1.5
  verbose: false
locale: pt-BR